
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.BorderFactory;
import java.text.DecimalFormat;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER VX 15 PREDATOR
 */
public class Form1 extends javax.swing.JFrame implements KeyListener{

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
        getContentPane().setBackground(new Color(242, 242, 242));
        jPanel1.setBackground(new Color(242, 242, 242));
        jPanel2.setBackground(new Color(242, 242, 242));
        jPanel3.setBackground(new Color(242, 242, 242));
        jPanel4.setBackground(new Color(242, 242, 242));
        jList1.setBackground(new Color(242, 242, 242));
        jList1.setModel(listI);
        DefaultListCellRenderer renderer =  (DefaultListCellRenderer)jList1.getCellRenderer();  
        renderer.setHorizontalAlignment(JLabel.RIGHT);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        addKeyListener(this);
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblMini = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnEq = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btnSq = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblDisplay = new javax.swing.JLabel();
        lblDside = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(500, 250));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Standard");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_history_schedule_time-512.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Calculator");

        lblMini.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMini.setText("-");
        lblMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMiniMouseExited(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("×");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMini, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        btn5.setBackground(new java.awt.Color(204, 204, 204));
        btn5.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn5.setFocusable(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(204, 204, 204));
        btn6.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn6.setFocusable(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn1.setFocusable(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn2.setFocusable(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn3.setFocusable(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(204, 204, 204));
        btn0.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn0.setFocusable(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnKali.setBackground(new java.awt.Color(180, 180, 180));
        btnKali.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnKali.setText("×");
        btnKali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKali.setFocusable(false);
        btnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaliActionPerformed(evt);
            }
        });

        btnKurang.setBackground(new java.awt.Color(180, 180, 180));
        btnKurang.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnKurang.setText("-");
        btnKurang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKurang.setFocusable(false);
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(180, 180, 180));
        btnTambah.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnTambah.setText("+");
        btnTambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTambah.setFocusable(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnComa.setBackground(new java.awt.Color(204, 204, 204));
        btnComa.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnComa.setText(",");
        btnComa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnComa.setFocusable(false);
        btnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComaActionPerformed(evt);
            }
        });

        btnEq.setBackground(java.awt.SystemColor.activeCaption);
        btnEq.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnEq.setText("=");
        btnEq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEq.setFocusable(false);
        btnEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqActionPerformed(evt);
            }
        });

        btnM.setBackground(new java.awt.Color(204, 204, 204));
        btnM.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnM.setText("+/-");
        btnM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnM.setFocusable(false);
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(180, 180, 180));
        btnClear.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnClear.setText("C");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.setFocusable(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnPercent.setBackground(new java.awt.Color(180, 180, 180));
        btnPercent.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnPercent.setText("%");
        btnPercent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPercent.setFocusable(false);
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });

        btnSq.setBackground(new java.awt.Color(180, 180, 180));
        btnSq.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnSq.setText("a²");
        btnSq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSq.setFocusable(false);
        btnSq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqActionPerformed(evt);
            }
        });

        btnBagi.setBackground(new java.awt.Color(180, 180, 180));
        btnBagi.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnBagi.setText("÷");
        btnBagi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBagi.setFocusable(false);
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(204, 204, 204));
        btn7.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn7.setFocusable(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(204, 204, 204));
        btn8.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn8.setFocusable(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(204, 204, 204));
        btn9.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn9.setFocusable(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(204, 204, 204));
        btn4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn4.setFocusable(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSq, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnComa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEq, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        jList1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, "card3");

        lblDisplay.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisplay.setText("0");
        lblDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDisplayMouseReleased(evt);
            }
        });

        lblDside.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblDside.setForeground(java.awt.Color.darkGray);
        lblDside.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDisplay)))
                .addGap(36, 36, 36))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(lblDside)
                .addGap(18, 18, 18)
                .addComponent(lblDisplay)
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        lblClose.setOpaque(true);
        lblClose.setBackground(Color.red);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseEntered
        // TODO add your handling code here:
        lblMini.setOpaque(true);
        lblMini.setBackground(Color.lightGray);
    }//GEN-LAST:event_lblMiniMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setBackground(new Color(242, 242, 242));
        lblClose.setForeground(Color.black);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseExited
        // TODO add your handling code here:
        lblMini.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_lblMiniMouseExited

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        setOpacity((float)0.93);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_formWindowLostFocus

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        if(!stateHistory){
            jLabel2.setOpaque(true);
            jLabel2.setBackground(Color.lightGray);
        }
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        if(!stateHistory){
            jLabel2.setBackground(new Color(242, 242, 242));
        }
    }//GEN-LAST:event_jLabel2MouseExited

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        tmblAngka("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        tmblAngka("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        tmblAngka("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComaActionPerformed
        // TODO add your handling code here:
        tmblComa();
    }//GEN-LAST:event_btnComaActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        // TODO add your handling code here:
       tmblM();
    }//GEN-LAST:event_btnMActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        tmblAngka("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        tmblAngka("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        tmblAngka("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        tmblAngka("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        tmblAngka("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        tmblAngka("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        tmbl0();
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        resetState();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        tmblOpt('+');
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqActionPerformed
        // TODO add your handling code here:
        tmblEq();
    }//GEN-LAST:event_btnEqActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
        tmblOpt('-');
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        // TODO add your handling code here:
        tmblOpt('×');
    }//GEN-LAST:event_btnKaliActionPerformed

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        // TODO add your handling code here:
        tmblOpt('÷');
    }//GEN-LAST:event_btnBagiActionPerformed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "BejjoCalcu - Aldhiya Rozak", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseClicked
        // TODO add your handling code here:
        setState(Form1.ICONIFIED);
    }//GEN-LAST:event_lblMiniMouseClicked

    private void lblDisplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDisplayMouseReleased
        // TODO add your handling code here:
        StringSelection stringSelection = new StringSelection(numDisplay);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        JOptionPane.showMessageDialog(null, "Copied!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblDisplayMouseReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        getContentPane().setBackground(new Color(153,153,153));
        jLabel2.setBackground(new Color(153,153,153));
        jPanel2.add(jPanel3);
        if(stateHistory){
            listI.clear();
        }
        else{
            jLabel2.setIcon(new ImageIcon(getClass().getResource("trash-512.png")));
            stateHistory = true;
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        getContentPane().setBackground(new Color(242,242,242));
        jLabel2.setBackground(new Color(242,242,242));
        jPanel2.add(jPanel4);
        jList1.clearSelection();
        stateHistory = false;
        jLabel2.setIcon(new ImageIcon(getClass().getResource("ui_history_schedule_time-512.png")));
    }//GEN-LAST:event_formMousePressed

    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentActionPerformed
        // TODO add your handling code here:
        tmblOpt('%');
    }//GEN-LAST:event_btnPercentActionPerformed

    private void btnSqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqActionPerformed
        // TODO add your handling code here:
        tmblOpt('²');
    }//GEN-LAST:event_btnSqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }
    private void addItem(String elmnt){
        listI.addElement(elmnt);
    }
    private void overflow(){
        if(lblDisplay.getText().length()>18){
            lblDisplay.setText("Overflow");
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
            btnPercent.setEnabled(false);
            btnSq.setEnabled(false);
            btnBagi.setEnabled(false);
            btnKali.setEnabled(false);
            btnKurang.setEnabled(false);
            btnTambah.setEnabled(false);
            btnM.setEnabled(false);
            btnComa.setEnabled(false);
            stateOver = true;
        }
    }
    private void tmblEq(){
        if(!stateOver){
            if(!stateEq){
                double temp;
                temp = numActual;
                numActual = tempActual;
                tempActual = temp;
            }
            double temps = numActual;
            switch(operator) {
                case '+':
                    numActual += tempActual;
                    lblDside.setText(df1.format(temps)+'+'+df1.format(tempActual)+'=');
                    lblDisplay.setText(df.format(numActual));
                    break;
                case '-':
                    numActual -= tempActual;
                    lblDside.setText(df1.format(temps)+'-'+df1.format(tempActual)+'=');
                    lblDisplay.setText(df.format(numActual));
                    break;
                case '×':
                    numActual *= tempActual;
                    lblDside.setText(df1.format(temps)+'×'+df1.format(tempActual)+'=');
                    lblDisplay.setText(df.format(numActual));
                    break;
                case '÷':
                    numActual /= tempActual;
                    lblDside.setText(df1.format(temps)+'÷'+df1.format(tempActual)+'=');
                    lblDisplay.setText(df.format(numActual));
                    break;
            }
            numDisplay="0";
            stateEq = true;
            stateComa = false;
            stateMin = false;
            sizing();
            addItem(lblDside.getText()+df.format(numActual));
        }
        else{
            resetState();
        }
        sizing();
        
    }
    private void tmblOpt(char opt){
        if(opt=='%'||opt=='²'){
            tempActual = numActual;
            lblDside.setText(df1.format(tempActual)+opt);
            operator=opt;
            double temp = tempActual;
            eqs();
            addItem(df1.format(temp)+opt+'='+df.format(tempActual));
            numDisplay = "0";
        }
        else{
            if(operator!=opt || stateEq){
                if(numDisplay!="0"){
                    eqs();
                }
                tempActual = numActual;
                lblDside.setText(df1.format(tempActual)+opt);
                operator=opt;
            }
            else if(numDisplay!="0"){
                eqs();
                addItem(df1.format(numActual-Double.valueOf(numDisplay))+opt+df1.format(Double.valueOf(numDisplay))+'='+df.format(numActual));
            }
            
            numDisplay = "0";
            stateComa = false;
            stateMin = false;
            stateEq = false;
        }
        sizing();
    }
    private void resetState(){
        lblDisplay.setText("0");
        btn0.setEnabled(true);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btnPercent.setEnabled(true);
        btnSq.setEnabled(true);
        btnBagi.setEnabled(true);
        btnKali.setEnabled(true);
        btnKurang.setEnabled(true);
        btnTambah.setEnabled(true);
        btnM.setEnabled(true);
        btnComa.setEnabled(true);
        stateOver = false;
        
        lblDside.setText("");
        numDisplay = "0";
        operator = ' ';
        numActual = 0;
        tempActual = 0;
        stateComa = false;
        stateMin = false;
        stateEq = false;
        stateOver = false;
        specialZero = ",0";
        
        lblDisplay.setFont(new Font(lblDisplay.getFont().getName(), Font.PLAIN, 48));
    }
    private void eqs(){
        double temp = numActual;
        switch(operator) {
            case '+':
                numActual += tempActual;
                tempActual = numActual;
                lblDside.setText(df1.format(numActual)+'+');
                lblDisplay.setText(df.format(numActual));
                break;
            case '-':
                numActual = tempActual - numActual;
                tempActual = numActual;
                lblDside.setText(df1.format(numActual)+'-');
                lblDisplay.setText(df.format(numActual));
                break;
            case '×':
                numActual *= tempActual;
                tempActual = numActual;
                lblDside.setText(df1.format(numActual)+'×');
                lblDisplay.setText(df.format(numActual));
                break;
            case '÷':
                numActual = tempActual / numActual;
                tempActual = numActual;
                lblDside.setText(df1.format(numActual)+'÷');
                lblDisplay.setText(df.format(numActual));
                break;
            case '%':
                numActual /= 100;
                tempActual = numActual;
                lblDside.setText(df1.format(temp)+"%=");
                lblDisplay.setText(df.format(numActual));
                operator = ' ';
                break;
            case '²':
                numActual *= numActual;
                tempActual = numActual;
                lblDside.setText(df1.format(temp)+"²=");
                lblDisplay.setText(df.format(numActual));
                operator = ' ';
                break;
        }
        sizing();
    }
    private void sizing(){
        System.out.println(lblDisplay.getSize().width);
        if(lblDisplay.getSize().width>298){
            lblDisplay.setFont(new Font(lblDisplay.getFont().getName(), Font.PLAIN, lblDisplay.getFont().getSize()-5));
        }
        //bug
//        if(lblDisplay.getSize().width>200 && lblDisplay.getText().length()>11){
//            lblDisplay.setFont(new Font(lblDisplay.getFont().getName(), Font.PLAIN, lblDisplay.getFont().getSize()-5));
//        }
        overflow();
    }
    private void tmblComa(){
        if(numDisplay.length()<13){
            if(!stateComa){
                lblDisplay.setText(df.format(Double.parseDouble(numDisplay))+",");
                stateComa = true;
                numDisplay += ".";
            }
            sizing();
        }
    }
    private void tmblM(){
        if(lblDisplay.getText()!="0"){
            if(stateMin){
                numDisplay = numDisplay.substring(1);
                lblDisplay.setText(df.format(Double.parseDouble(numDisplay)));
                stateMin = false;
                numActual *= -1;
            }
            else{
                numDisplay = "-"+ numDisplay;
                lblDisplay.setText(df.format(Double.parseDouble(numDisplay)));
                stateMin = true;
                numActual *= -1;
            }
            sizing();
        }
    }
    private void tmblAngka(String angka){
        if(numDisplay.length()<13){
            if(lblDisplay.getText()=="0"){
                numDisplay = angka;
                lblDisplay.setText(df.format(Integer.parseInt(numDisplay)));
                numActual = Double.parseDouble(numDisplay);
            }
            else{
                numDisplay+=angka;
                lblDisplay.setText(df.format(Double.parseDouble(numDisplay)));
                numActual = Double.parseDouble(numDisplay);
            }
            sizing();
        }
    }
    private void tmbl0(){
        if(numDisplay.length()<13){
            if(lblDisplay.getText()!="0"){
                numDisplay+="0";
                if(stateComa){
                    if(lblDisplay.getText().charAt(lblDisplay.getText().length()-1)==','||lblDisplay.getText().charAt(lblDisplay.getText().length()-1)=='0'){
                        lblDisplay.setText(df.format(Double.parseDouble(numDisplay))+specialZero);
                        specialZero+="0";
                    }
                    else{
                        specialZero="0";
                        lblDisplay.setText(df.format(Double.parseDouble(numDisplay))+specialZero);
                        specialZero+="0";
                    }
                }
                else{
                    lblDisplay.setText(df.format(Double.parseDouble(numDisplay)));
                }
                numActual = Double.parseDouble(numDisplay);
            }
            sizing();
        }
    }
    
    private DefaultListModel listI = new DefaultListModel();;
    private final DecimalFormat df = new DecimalFormat("###,###.#############");
    private final DecimalFormat df1 = new DecimalFormat("###.#############");
    private int xy,xx;
    private String numDisplay = "0";
    private char operator = ' ';
    private double numActual = 0;
    private double tempActual = 0;
    private boolean stateComa = false;
    private boolean stateMin = false;
    private boolean stateEq = false;
    private boolean stateOver = false;
    private boolean stateHistory = false;
    private String specialZero = ",0";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnEq;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnSq;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblDside;
    private javax.swing.JLabel lblMini;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if(!stateOver){
            if(e.getKeyCode()==KeyEvent.VK_1)    
            {
                btn1.setBackground(new Color(153,153,153));
                tmblAngka("1");
            }
            if(e.getKeyCode()==KeyEvent.VK_2)    
            {
                btn2.setBackground(new Color(153,153,153));
                tmblAngka("2");
            }
            if(e.getKeyCode()==KeyEvent.VK_3)    
            {
                btn3.setBackground(new Color(153,153,153));
                tmblAngka("3");
            }
            if(e.getKeyCode()==KeyEvent.VK_4)    
            {
                btn4.setBackground(new Color(153,153,153));
                tmblAngka("4");
            }
            if(e.getKeyCode()==KeyEvent.VK_5 && !e.isShiftDown())    
            {
                btn5.setBackground(new Color(153,153,153));
                tmblAngka("5");
            }
            if(e.getKeyCode()==KeyEvent.VK_6)    
            {
                btn6.setBackground(new Color(153,153,153));
                tmblAngka("6");
            }
            if(e.getKeyCode()==KeyEvent.VK_7)    
            {
                btn7.setBackground(new Color(153,153,153));
                tmblAngka("7");
            }
            if(e.getKeyCode()==KeyEvent.VK_8 && !e.isShiftDown())    
            {
                btn8.setBackground(new Color(153,153,153));
                tmblAngka("8");
            }
            if(e.getKeyCode()==KeyEvent.VK_9)    
            {
                btn9.setBackground(new Color(153,153,153));
                tmblAngka("9");
            }
            if(e.getKeyCode()==KeyEvent.VK_0)    
            {
                btn0.setBackground(new Color(153,153,153));
                tmbl0();
            }


            if(e.getKeyCode()==KeyEvent.VK_COMMA)    
            {
                btnComa.setBackground(new Color(150,150,150));
                tmblComa();
            }
            if(e.getKeyCode()==KeyEvent.VK_C)    
            {
                btnClear.setBackground(new Color(150,150,150));
                resetState();
            }        
            if(e.getKeyCode()==KeyEvent.VK_5 && e.isShiftDown())    
            {
                btnPercent.setBackground(new Color(150,150,150));
            }
            if(e.getKeyCode()==KeyEvent.VK_Q)    
            {
                btnSq.setBackground(new Color(150,150,150));
            }
            if(e.getKeyCode()==KeyEvent.VK_SLASH)    
            {
                btnBagi.setBackground(new Color(150,150,150));
                tmblOpt('÷');
            }
            if(e.getKeyCode()==KeyEvent.VK_8 && e.isShiftDown())    
            {
                btnKali.setBackground(new Color(150,150,150));
                tmblOpt('×');
            }
            if(e.getKeyCode()==KeyEvent.VK_MINUS)    
            {
                btnKurang.setBackground(new Color(150,150,150));
                tmblOpt('-');
            }
            if(e.getKeyCode()==KeyEvent.VK_EQUALS && e.isShiftDown())    
            {
                btnTambah.setBackground(new Color(150,150,150));
                tmblOpt('+');
            }
            if((e.getKeyCode()==KeyEvent.VK_EQUALS && !e.isShiftDown()) || (e.getKeyCode()==KeyEvent.VK_ENTER)) 
            {
                btnEq.setBackground(new Color(153,178,245));
                tmblEq();
            }
            if(e.getKeyCode()==KeyEvent.VK_M)    
            {
                btnM.setBackground(new Color(153,153,153));
                tmblM();
            }
        }
        else{
            resetState();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        btnM.setBackground(new Color(204,204,204));
        btn1.setBackground(new Color(204,204,204));
        btn2.setBackground(new Color(204,204,204));
        btn3.setBackground(new Color(204,204,204));
        btn4.setBackground(new Color(204,204,204));
        btn5.setBackground(new Color(204,204,204));
        btn6.setBackground(new Color(204,204,204));
        btn7.setBackground(new Color(204,204,204));
        btn8.setBackground(new Color(204,204,204));
        btn9.setBackground(new Color(204,204,204));
        btn0.setBackground(new Color(204,204,204));
        btnComa.setBackground(new Color(204,204,204));
        btnClear.setBackground(new Color(180,180,180));
        btnPercent.setBackground(new Color(180,180,180));
        btnSq.setBackground(new Color(180,180,180));
        btnBagi.setBackground(new Color(180,180,180));
        btnKali.setBackground(new Color(180,180,180));
        btnKurang.setBackground(new Color(180,180,180));
        btnTambah.setBackground(new Color(180,180,180));
        btnEq.setBackground(new Color(153,180,209));
    }
}
